name: Full Pipeline (Infra + App)

on:
  push:
    branches:
      - main
      - feature/setup-terraform
  workflow_dispatch:

env:
  TARGET_ENV: ${{ github.ref == 'main' && 'prod' || 'dev'}}
  PROJECT_NAME: "myproject"
  AWS_region: "eu-central-1"

jobs:
  terraform:
    name: Infrastructure (${{ github.ref == 'main' && 'Prod' || 'Dev'}})
    runs-on: ubuntu-latest
    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD}}
    defaults:
      run:
        working-directory: infra/environments/${{ github.ref == 'main' && 'prod' || 'dev'}}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
  
  deploy:
    name: Application Deploy (${{ github.ref == 'main' && 'Prod' || 'Dev'}})
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Pack Apllication
        run: |
          cd app
          zip -r ../app.zip .

      - name: Get Dynamic Bucket Name
        id: find_bucket
        run: |
          echo "Searching for bucket for ${{ env.TARGET_ENV }}..."
          for i in {1..21}; do
            BUCKET_NAME=$(aws resourcegroupstaggingapi get-resources \
              --tag-filters Key=Project,Values=myproject Key=Environment,Values=dev Key=Type,Values=ArtifactStorage \
              --resource-type-filters s3 \
              --query 'ResourceTagMappingList[0].ResourceARN' \
              --output text | cut -d: -f6)

            if [ -n "$BUCKET_NAME" ] && [ "$BUCKET_NAME" != "None" ]; then
              echo "Found bucket: $BUCKET_NAME"
              echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Waiting for AWS to index tags... (Attempt $i/21)"
            sleep 20
          done
          echo "Error: Bucket not found after 7 minutes."
          exit 1

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://${{ steps.find_bucket.outputs.bucket_name }}/app.zip

      - name: Find ASG Name
        id: find_asg
        run: |
          ASG_NAME=$(aws autoscaling describe-auto-scaling-groups \
            --query "AutoScalingGroups[?contains(Tags[?Key=='Project'].Value, '${{ env.PROJECT_NAME}}') && contains(Tags[?Key=='Environment'].Value, '${{ env.TARGET_ENV }}')].AutoScalingGroupName" \
            --output text)

          if [ -z "$ASG_NAME" ] || [ "$ASG_NAME" == "None" ]; then
            echo "Error: ASG for ${{ env.TARGET_ENV }} not found!"
            exit 1
          fi

          echo "Found ASG: $ASG_NAME"
          echo "asg_name=$ASG_NAME" >> $GITHUB_OUTPUT

      - name: Start Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ steps.find_asg.outputs.asg_name }} \
            --preferences '{"MinHealthyPercentage": 100, "InstanceWarmup": 300}'